package KieRule
import com.javatechie.spring.drools.api.Core;
import com.javatechie.spring.drools.api.Tehnika;
import com.javatechie.spring.drools.api.PodTehnika;
import com.javatechie.spring.drools.api.Raspored;
import com.javatechie.spring.drools.api.Lista
import java.util.Date;

dialect  "mvel"


rule "Preko100"
    when
        $t: Tehnika($t.getPrioritet() > 100)
    then
        $t.setPrioritet(100);
end

rule "Ispod0"
    when
        $t: Tehnika($t.getPrioritet() < 0)
    then
        $t.setPrioritet(0);
end


rule "SavladaoViseOd100"
    when
        $pt: PodTehnika($pt.getSavadao() > 100)
    then
        $pt.setSavadao(100);
    end



///////////////////////////////////////////////////////////////////////  presao.drl



rule "NovuTehnikuSve"
    when
        $t: Tehnika($pt:podtehnike, $presao: presao, $prioritet: prioritet, $podtehnika: getPodtehnika(), $procenat:getProcenat() <= 25)
        $min: Integer($min>=20)
    then
        $t.setPrioritet($t.getPrioritet() + 2);
        $t.setPresao(new Date());
        $podtehnika.setSavadao($podtehnika.getSavadao() + $podtehnika.getKorak());
end

rule "NovuTehnikuPola"
    when
        $t: Tehnika($pt:podtehnike, $presao: presao, $prioritet: prioritet, $podtehnika: getPodtehnika(), $procenat:getProcenat() <= 25)
        $min: Integer($min>=5 && $min<20)
    then
        $t.setPrioritet($t.getPrioritet() + 1);
        $t.setPresao(new Date());
        $podtehnika.setSavadao($podtehnika.getSavadao() + ($podtehnika.getKorak()/2));
end

rule "NovuTehnikuSlabo"
    when
        $t: Tehnika($pt:podtehnike, $presao: presao, $prioritet: prioritet, $podtehnika: getPodtehnika(), $procenat:getProcenat() <= 25)
        $min: Integer($min<5)
    then
        $t.setPrioritet($t.getPrioritet() - 1);
        $t.setPresao(new Date());
        $podtehnika.setSavadao($podtehnika.getSavadao() + ($podtehnika.getKorak()/4));
end


rule "PoznatuTehnikuSve"
    when
        $t: Tehnika($pt:podtehnike, $presao: presao, $prioritet: prioritet, $podtehnika: getPodtehnika(), $procenat:getProcenat() <= 50, getProcenat() > 25)
        $min: Integer($min>=50)
    then
        $t.setPrioritet($t.getPrioritet() + 2);
        $t.setPresao(new Date());
        $podtehnika.setSavadao($podtehnika.getSavadao() + $podtehnika.getKorak());
end

rule "PoznatuTehnikuPola"
    when
        $t: Tehnika($pt:podtehnike, $presao: presao, $prioritet: prioritet, $podtehnika: getPodtehnika(), $procenat:getProcenat() <= 50, getProcenat() > 25)
        $min: Integer($min>=15 && $min<50)
    then
        $t.setPrioritet($t.getPrioritet() + 1);
        $t.setPresao(new Date());
        $podtehnika.setSavadao($podtehnika.getSavadao() + ($podtehnika.getKorak()/2));
end

rule "PoznatuTehnikuSlabo"
    when
        $t: Tehnika($pt:podtehnike, $presao: presao, $prioritet: prioritet, $podtehnika: getPodtehnika(), $procenat:getProcenat() <= 50, getProcenat() > 25)
        $min: Integer($min<15)
    then
        $t.setPrioritet($t.getPrioritet() - 1);
        $t.setPresao(new Date());
        $podtehnika.setSavadao($podtehnika.getSavadao() + ($podtehnika.getKorak()/4));
end


rule "RazradjenuTehnikuSve"
    when
        $t: Tehnika($pt:podtehnike, $presao: presao, $prioritet: prioritet, $podtehnika: getPodtehnika(), $procenat:getProcenat() > 50)
        $min: Integer($min>=100)
    then
        $t.setPrioritet($t.getPrioritet() + 2);
        $t.setPresao(new Date());
        $podtehnika.setSavadao($podtehnika.getSavadao() + $podtehnika.getKorak());
end

rule "RazradjenuTehnikuPola"
    when
        $t: Tehnika($pt:podtehnike, $presao: presao, $prioritet: prioritet, $podtehnika: getPodtehnika(), $procenat:getProcenat() > 50)
        $min: Integer($min>=30 && $min<100)
    then
        $t.setPrioritet($t.getPrioritet() + 1);
        $t.setPresao(new Date());
        $podtehnika.setSavadao($podtehnika.getSavadao() + ($podtehnika.getKorak()/2));
end

rule "RazradjenuTehnikuSlabo"
    when
        $t: Tehnika($pt:podtehnike, $presao: presao, $prioritet: prioritet, $podtehnika: getPodtehnika(), $procenat:getProcenat() > 50)
        $min: Integer($min>30)
    then
        $t.setPrioritet($t.getPrioritet() - 1);
        $t.setPresao(new Date());
        $podtehnika.setSavadao($podtehnika.getSavadao() + ($podtehnika.getKorak()/4));
end


rule "Prskocio"
    when
        $t: Tehnika($pt:podtehnike, $presao: presao, $prioritet: prioritet)
        $min: Integer($min==0)
    then
        $t.setPrioritet($t.getPrioritet() - 5);
end


rule "Pravac"
    when
        $core: Core($tehnike: tehnike)
        $pravac: String()//$pravac == "Bas")// e.g.
        $pravci: Lista($tags : elementi contains $pravac)
    then
        $core.setPravac($pravac);
end



///////////////////////////////////////////////////////////////////////  zvuk.drl



rule "Zvuk"// da li treba da promeni br zadataka ovde?
    when
        $core: Core($tehnike: tehnike)
        $zvuk: String()//$zvuk == "Rock")// e.g.
        $zvukoci: Lista($tags : elementi contains $zvuk)
    then
        $core.setZvuk($zvuk);
end



///////////////////////////////////////////////////////////////////////  raspored.drl



rule "Raspored1Poc"
    when
        $core: Core($core.getSavladanost(0) <= 25.0)// sta ako nema 3 slobodne tehnike
        $raspored: Raspored($zadaci: zadaci contains "Zadatak1")
    then
        $raspored.addZadatak(0, "Vezbaj " + $core.getZadatak(0) + " 30min");
end

rule "Raspored1Sred"
    when
        $core: Core($core.getSavladanost(0) <= 50.0 && $core.getSavladanost(0) > 25)
        $raspored: Raspored($zadaci: zadaci contains "Zadatak1")
    then
        $raspored.addZadatak(0, "Vezbaj " + $core.getZadatak(0) + " 1h");
end

rule "Raspored1Kraj"
    when
        $core: Core($core.getSavladanost(0) > 50.0)
        $raspored: Raspored($zadaci: zadaci contains "Zadatak1")
    then
        $raspored.addZadatak(0, "Vezbaj " + $core.getZadatak(0) + " 2h");
end


rule "Raspored2Poc"
    when
        $core: Core($core.getSavladanost(1) <= 25.0)// sta ako nema 3 slobodne tehnike
        $raspored: Raspored($zadaci: zadaci contains "Zadatak2")
    then
        $raspored.addZadatak(1, "Vezbaj " + $core.getZadatak(1) + " 30min");
end

rule "Raspored2Sred"
    when
        $core: Core($core.getSavladanost(1) <= 50.0 && $core.getSavladanost(1) > 25)
        $raspored: Raspored($zadaci: zadaci contains "Zadatak2")
    then
        $raspored.addZadatak(1, "Vezbaj " + $core.getZadatak(1) + " 1h");
end

rule "Raspored2Kraj"
    when
        $core: Core($core.getSavladanost(1) > 50.0)
        $raspored: Raspored($zadaci: zadaci contains "Zadatak2")
    then
        $raspored.addZadatak(1, "Vezbaj " + $core.getZadatak(1) + " 2h");
end


rule "Raspored3Poc"
    when
        $core: Core($core.getSavladanost(2) <= 25.0)// sta ako nema 3 slobodne tehnike
        $raspored: Raspored($zadaci: zadaci contains "Zadatak3")
    then
        $raspored.addZadatak(2, "Vezbaj " + $core.getZadatak(2) + " 30min");
end

rule "Raspored3Sred"
    when
        $core: Core($core.getSavladanost(2) <= 50.0 && $core.getSavladanost(2) > 25)
        $raspored: Raspored($zadaci: zadaci contains "Zadatak3")
    then
        $raspored.addZadatak(2, "Vezbaj " + $core.getZadatak(2) + " 1h");
end

rule "Raspored3Kraj"
    when
        $core: Core($core.getSavladanost(2) > 50.0)
        $raspored: Raspored($zadaci: zadaci contains "Zadatak3")
    then
        $raspored.addZadatak(2, "Vezbaj " + $core.getZadatak(2) + " 2h");
end


rule "CustomTehnikaPoc"
    when
        $tip: String($tip == "Custom")
        $id : Integer()
        $core: Core($core.getSavladanost($id) <= 25.0)
        $raspored: Raspored()
    then
        $raspored.addZadatak(3, "Vezbaj " + $core.getZadatak($id) + " 30min");
end

rule "CustomTehnikaSred"
    when
        $tip: String($tip == "Custom")
        $id : Integer()
        $core: Core($core.getSavladanost($id) <= 50.0 && $core.getSavladanost($id) > 25)
        $raspored: Raspored()
    then
        $raspored.addZadatak(3, "Vezbaj " + $core.getZadatak($id) + " 1h");
end

rule "CustomTehnikaKraj"
    when
        $t: Tehnika()
        $tip: String($tip == "Custom")
        $id : Integer()
        $core: Core($core.getSavladanost($id) > 50.0)
        $raspored: Raspored()
    then
        $raspored.addZadatak(3, "Vezbaj " + $core.getZadatak($id) + " 2h");
end


/////////////////////////////////////////////////////////////////////////////////



rule "Legacy"
    when
        $core: Core()
        $idl: Integer($core.getStara() != -1)
        $raspored: Raspored()
    then
     $raspored.addZadatak(4, "Vezbaj " + $core.getZadatak($idl) + " 30min");
end